# Generated by Django 4.2.1 on 2023-09-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scuola_vela', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uscita',
            old_name='ora_entrata',
            new_name='ora_rientro',
        ),
    ]
