# Generated by Django 4.2.1 on 2023-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuola_vela', '0002_rename_ora_entrata_uscita_ora_rientro'),
    ]

    operations = [
        migrations.AddField(
            model_name='allievo',
            name='ol',
            field=models.CharField(choices=[('optimist', 'Optimist'), ('laser', 'Laser')], default='optimist', max_length=100),
        ),
        migrations.AddField(
            model_name='uscita',
            name='ol',
            field=models.CharField(choices=[('optimist', 'Optimist'), ('laser', 'Laser')], default='optimist', max_length=100),
        ),
    ]
