# Generated by Django 4.2.1 on 2023-09-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='stato',
            field=models.CharField(choices=[('Inviato', 'Inviato'), ('In elaborazione', 'In elaborazione'), ('Risolto', 'Risolto')], max_length=50),
        ),
    ]
